text:
- "&eWelcome to SurvivalCraft! "
- "&e Welcome to SurvivalCraft!"
- "&e! Welcome to SurvivalCraft"
- "&et! Welcome to SurvivalCraf"
- "&eft! Welcome to SurvivalCra"
- "&eaft! Welcome to SurvivalCr"
- "&eraft! Welcome to SurvivalC"
- "&eCraft! Welcome to Survival"
- "&elCraft! Welcome to Surviva"
- "&ealCraft! Welcome to Surviv"
- "&evalCraft! Welcome to Survi"
- "&eivalCraft! Welcome to Surv"
- "&evivalCraft! Welcome to Sur"
- "&ervivalCraft! Welcome to Su"
- "&eurvivalCraft! Welcome to S"
- "&eSurvivalCraft! Welcome to "
- "&e SurvivalCraft! Welcome to"
- "&eo SurvivalCraft! Welcome t"
- "&eto SurvivalCraft! Welcome "
- "&e to SurvivalCraft! Welcome"
- "&ee to SurvivalCraft! Welcom"
- "&eme to SurvivalCraft! Welco"
- "&eome to SurvivalCraft! Welc"
- "&ecome to SurvivalCraft! Wel"
- "&elcome to SurvivalCraft! We"
- "&eelcome to SurvivalCraft! W"
- "&eWelcome to SurvivalCraft! "

interval: 2
random: false

offset-lines: 10
# 0 = loop, 1 = reverse loop
animation-type: 1
